
# This is a basic workflow to help you get started with Actions

name: Deploy to Raspberry Pi

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  workflow_run:
    workflows: [test]
    types: 
      - completed
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  on-success:
    # The type of runner that the job will run on
    runs-on: [self-hosted, Linux, ARM64, rpi3, testbuild]
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Setup virtual env, install dependencies
      - name: Build Container and Run App
        run:  |
          docker build -t customer_api:latest --target base .
  on-failure:
    runs-on: [self-hosted, Linux, ARM64, rpi3, testbuild]
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'

          
