
# This is a basic workflow to help you get started with Actions

name: Deploy Testing 

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  FLASK_APP: app.py

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Setup virtual env, install dependencies
      - name: Build Test Docker Container for Customer API
        run:  |
          docker build --build-arg BUILD_ENV=ci-testing -t customer_api:testing .

      - name: clear testing Constainer
        run:  |
          docker rmi -f $(docker images -f=reference='customer_api:testing' --format "{{.ID}}")
 